export const COFFEE_BRANDS = 'COFFEE_BRANDS';
export const COFFEE_BRANDS_FACTORY = 'COFFEE_BRANDS_FACTORY';
export const COFFEE_BRANDS_FACTORY_PROVIDER = 'COFFEE_BRANDS_FACTORY_PROVIDER';
export const COFFEE_BRANDS_ASYNC = 'COFFEE_BRANDS_ASYNC';
