services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - db_data:/var/lib/postgresql

  test-db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - test_db_data:/var/lib/postgresql

volumes:
  db_data:
  test_db_data:
